spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: yourself password


#开启驼峰命名和下划线命名的自动转换，为了可以识取user表中create_time和update_time字段，User类中是createTime和updateTime
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8989